baseURL = "https://stalwart-pastelito-a61597.netlify.app"
languageCode = "de"
title = "Tagesbonus - T채glich spins, coins und mehr!"

defaultContentLanguage = "de"
[languages]
  [languages.de]
    languageName = "Deutsch"
    dateFormat = "2. January 2006"

[taxonomies]
  tag = "tags"

[permalinks]
post = "/:slug/"

[params]
  description = "Erhalten Sie t채glich Freispiele, M체nzen und Boni f체r Spiele. Sofortiger Zugriff auf die neuesten Promo-Links. Verbessern Sie Ihr Spiel!"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
