baseURL = "https://stalwart-pastelito-a61597.netlify.app"
languageCode = "en-us"
title = "Tages Bonus"

[taxonomies]
  category = "categories"
  tag = "tags"

[build]
  useResourceCacheWhen = "always"

[frontmatter]
  lastmod = ["git", "lastmod", "date"]

[permalinks]
post = "/:slug/"

