baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Hugo Site"

[params]
  mainSections = ["free-dice", "free-coin"]

[taxonomies]
  category = "categories"
  tag = "tags"

[frontmatter]
lastmod = ["git", "fileModTime"]
